### ISSUE TITLE
IML : selector does not work

### ISSUE THREAD

**Issue by vkopachinsky** [Incoding-Software/Incoding-Framework#130]
`
 dsl.With(r=>r.Class(textAreaClass).Filter(s=>s.Not(a=>a.Class(B.Hidden)))).JQuery.PlugIn("trumbowyg");
`

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by IncodingSoftware** [comment]
Problem because Not is MaybeExtensiions .
